version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  celery:
    build: .
    command: celery -A bike_rental worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - mynetwork
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis

networks:
  mynetwork:
    driver: bridge
